import { Boxes, Code2, HeartHandshake, ShieldCheck } from 'lucide-react'

const values = [
  { icon: Boxes, title: 'قابل للتوسعة', text: 'كل منصة موصوفة في Provider مستقل. أضف نطاقًا جديدًا ثم استخدم نفس مسار الاستخراج.' },
  { icon: Code2, title: 'منظم للمطورين', text: 'فصل واضح بين الواجهة وطبقة API وسجل التنزيلات، مع نماذج بيانات مصرح بها.' },
  { icon: ShieldCheck, title: 'الاستخدام المسؤول', text: 'المنصة مصممة للوسائط العامة التي تملكها أو لديك تصريح واضح بتنزيلها.' },
]

export default function AboutPage() { return <section className="mx-auto max-w-6xl px-5 pb-24 pt-16 lg:px-8"><div className="max-w-3xl"><span className="inline-flex items-center gap-2 text-sm font-medium text-cyan-300"><HeartHandshake size={19} /> عن MediaFlow</span><h1 className="mt-4 text-4xl font-bold leading-tight text-white sm:text-5xl">تجربة واحدة للتعامل مع روابط الوسائط.</h1><p className="mt-5 text-base leading-8 text-slate-400">MediaFlow هو قالب ويب حديث يختصر مسار المستخدم: رابط واحد، تعرّف تلقائي على المصدر، ثم تفاصيل واضحة للوسائط قبل اتخاذ أي إجراء.</p></div><div className="mt-14 grid gap-4 md:grid-cols-3">{values.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-2xl border border-white/[.08] bg-white/[.025] p-6"><div className="grid h-11 w-11 place-items-center rounded-xl bg-cyan-300/[.08] text-cyan-300"><Icon size={21} /></div><h2 className="mt-6 font-bold text-slate-100">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-500">{text}</p></article>)}</div><div className="mt-16 grid gap-8 border-t border-white/[.08] pt-12 md:grid-cols-2"><div><h2 className="text-xl font-bold">كيف تعمل؟</h2><ol className="mt-5 space-y-4 text-sm leading-7 text-slate-400"><li><strong className="ml-2 text-cyan-300">01</strong>ألصق رابط الوسائط العام.</li><li><strong className="ml-2 text-cyan-300">02</strong>تتعرف طبقة المزودات على المنصة تلقائيًا.</li><li><strong className="ml-2 text-cyan-300">03</strong>تجمع خدمة الاستخراج البيانات وخيارات الصيغ.</li><li><strong className="ml-2 text-cyan-300">04</strong>اختر جودة متاحة لتنزيل المحتوى المصرح به.</li></ol></div><div className="rounded-2xl border border-indigo-400/15 bg-indigo-400/[.05] p-6"><p className="text-sm font-semibold text-white">ملاحظة مهمة</p><p className="mt-3 text-sm leading-7 text-slate-400">تحقّق دائمًا من شروط المنصة وحقوق النشر قبل تنزيل المحتوى أو إعادة استخدامه. هذه الواجهة لا تمنح حقوقًا على أي محتوى خارجي.</p></div></div></section> }

