import { Braces, Check, Copy, KeyRound, Terminal } from 'lucide-react'
import { useState } from 'react'

const endpoint = `POST /api/v1/media/inspect\nContent-Type: application/json\n\n{\n  "url": "https://www.youtube.com/watch?v=..."\n}`
const response = `{\n  "platform": "YouTube",\n  "title": "عنوان الوسائط",\n  "thumbnail": "https://...",\n  "duration": 226,\n  "formats": [\n    { "id": "137", "label": "1080p · MP4", "kind": "video" }\n  ]\n}`

function CodeBlock({ children }) { const [copied, setCopied] = useState(false); return <div className="relative overflow-hidden rounded-xl border border-white/[.08] bg-[#080d1a] p-4" dir="ltr"><button onClick={() => { navigator.clipboard.writeText(children); setCopied(true); setTimeout(() => setCopied(false), 1500) }} className="absolute left-3 top-3 rounded p-1.5 text-slate-500 hover:bg-white/[.06] hover:text-white">{copied ? <Check size={15} /> : <Copy size={15} />}</button><pre className="overflow-x-auto text-left text-xs leading-6 text-cyan-100"><code>{children}</code></pre></div> }

export default function ApiPage() { return <section className="mx-auto max-w-6xl px-5 pb-24 pt-16 lg:px-8"><div className="max-w-2xl"><span className="inline-flex items-center gap-2 text-sm font-medium text-cyan-300"><Braces size={19} /> للمطورين</span><h1 className="mt-4 text-4xl font-bold text-white">API بسيط، واضح، وقابل للتوسعة.</h1><p className="mt-4 leading-7 text-slate-400">افحص الرابط للحصول على بيانات الوسائط والخيارات المتاحة. طبقة المزودات مستقلة، لذا يمكن إضافة منصة جديدة دون تعديل الواجهة أو نقاط النهاية.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><aside className="space-y-4"><div className="rounded-2xl border border-white/[.08] bg-white/[.025] p-5"><Terminal className="text-cyan-300" size={21} /><h2 className="mt-4 font-semibold">نقطة الفحص</h2><p className="mt-2 text-sm leading-6 text-slate-500">تحلل الرابط وتعيد البيانات الوصفية والجودات.</p><code className="mt-4 block text-xs text-indigo-300">POST /media/inspect</code></div><div className="rounded-2xl border border-white/[.08] bg-white/[.025] p-5"><KeyRound className="text-cyan-300" size={21} /><h2 className="mt-4 font-semibold">التشغيل محليًا</h2><p className="mt-2 text-sm leading-6 text-slate-500">لا تحتاج النسخة المحلية لمفتاح API. أضف مصادقة قبل نشرها للعامة.</p></div></aside><div className="space-y-5"><div><p className="mb-2 text-sm font-semibold text-slate-300">الطلب</p><CodeBlock>{endpoint}</CodeBlock></div><div><p className="mb-2 text-sm font-semibold text-slate-300">الاستجابة</p><CodeBlock>{response}</CodeBlock></div></div></div><div className="mt-12 overflow-hidden rounded-2xl border border-white/[.08]"><table className="w-full text-right text-sm"><thead className="bg-white/[.04] text-slate-400"><tr><th className="px-5 py-3 font-medium">النقطة</th><th className="px-5 py-3 font-medium">الغرض</th></tr></thead><tbody className="divide-y divide-white/[.06] text-slate-300"><tr><td className="px-5 py-4 font-mono text-xs text-cyan-300">POST /media/inspect</td><td className="px-5 py-4">اكتشاف المنصة وقراءة معلومات الوسائط.</td></tr><tr><td className="px-5 py-4 font-mono text-xs text-cyan-300">POST /media/download</td><td className="px-5 py-4">بدء تنزيل الجودة المختارة وإرجاع رابط الملف.</td></tr><tr><td className="px-5 py-4 font-mono text-xs text-cyan-300">GET /recent</td><td className="px-5 py-4">عرض آخر عمليات التنزيل المحلية.</td></tr></tbody></table></div></section> }

